# **ANÁLISIS RENDIMIENTO ACADÉMICO**

In [ ]:
#Importar df. mostrar encabezados
import pandas as pd
df = pd.read_excel("datos_limpios_resu_P1_1003.xlsx")
df.head()

,Unnamed: 0,N°,Codigo,Estudiante,Electrónica jv1,Electrónica acum,Programación jv1,Programación acum,Lógica Matemática jv1,Lógica Matemática acum,...,Dibujo_jv1,Dibujo_acum,Teatro_jv1,Teatro_acum,Educación_Física_rd_jv1,Educación Física_rd_acum,Ingles_Avanzado _jv1,Ingles_Avanzado _acum,Convivencia_jv1,Unnamed: 37
0,NaN,1,2500352,ANAYA MARTINEZ SANTIAGO JOSE,3.3,0.82,2.8,0.70,2.2,0.55,...,4.5,1.12,3.1,0.77,3.6,0.90,2.8,0.70,AL,10.0
1,NaN,2,2210053,BENITEZ GUIRAL ISABELLA,3.7,0.92,2.8,0.70,3.5,0.87,...,4.5,1.12,3.5,0.87,3.2,0.80,3.1,0.77,AL,4.0
2,NaN,3,2300038,BENITEZ TIQUE VALENTINA,3.2,0.80,3.7,0.92,3.3,0.82,...,4.5,1.12,4.1,1.02,4.1,1.02,3.7,0.92,AL,1.0
3,NaN,4,2600054,BORRERO GALLEGO THOMAS,2.8,0.70,2.9,0.72,3.1,0.77,...,4.0,1.00,3.9,0.97,4.0,1.00,2.8,0.70,BS,11.0
4,NaN,5,2600055,BRITTON HOWARD ERICK JACOB,3.3,0.82,3.2,0.80,2.5,0.62,...,3.9,0.97,3.6,0.90,4.2,1.05,3.0,0.75,AL,2.0

Warning: Total number of columns (38) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
#PASO 2 — QUITAMOS TILDES.. de encabezados.

import unicodedata

def quitar_tildes(texto):
    return ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )

df.columns = [quitar_tildes(col) for col in df.columns]
#df.columns

In [ ]:
#PASO 3 _Revisamos (columnas vacias)
[col for col in df.columns if "Unnamed" in col]

[]

In [ ]:
#Eliminamos (columnas vacias)
df = df.drop(columns=['Unnamed: 0', 'Unnamed: 37'])

In [ ]:
df.columns

Index(['N°', 'Codigo', 'Estudiante', 'Electronica jv1', 'Electronica acum',
       'Programacion jv1', 'Programacion acum', 'Logica Matematica  jv1',
       'Logica Matematica  acum', 'Quimica jv1', 'Quimica_acum', 'Fisica jv1',
       'Fisica_acum', 'Trigonometria jv1', 'Trigonometria acum',
       'Informatica_Tecnologia_jv1', 'Informatica _Tecnologia acum',
       'Competencias_Ciudadanas jv1', 'Competencias_Ciudadanas_acum',
       'Ciencias Politicas  Economicas jv1',
       'Ciencias_Politicas _Economicas_acum', 'Filosofia jv1',
       'Filosofia_acum', 'Educacion_Etica_Religiosa jv1',
       'Educacion_Etica_Religiosa_acum', 'Lengua_Castellana_jv1',
       'Lengua_Castellana_acum', 'Dibujo_jv1', 'Dibujo_acum', 'Teatro_jv1',
       'Teatro_acum', 'Educacion_Fisica_rd_jv1', 'Educacion Fisica_rd_acum',
       'Ingles_Avanzado _jv1', 'Ingles_Avanzado _acum', 'Convivencia_jv1'],
      dtype='object')

In [ ]:
#PASO 4 — NORMALIZAR NOMBRES
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("__", "_")
)

In [ ]:
df.columns

Index(['n°', 'codigo', 'estudiante', 'electronica_jv1', 'electronica_acum',
       'programacion_jv1', 'programacion_acum', 'logica_matematica_jv1',
       'logica_matematica_acum', 'quimica_jv1', 'quimica_acum', 'fisica_jv1',
       'fisica_acum', 'trigonometria_jv1', 'trigonometria_acum',
       'informatica_tecnologia_jv1', 'informatica_tecnologia_acum',
       'competencias_ciudadanas_jv1', 'competencias_ciudadanas_acum',
       'ciencias_politicas_economicas_jv1',
       'ciencias_politicas_economicas_acum', 'filosofia_jv1', 'filosofia_acum',
       'educacion_etica_religiosa_jv1', 'educacion_etica_religiosa_acum',
       'lengua_castellana_jv1', 'lengua_castellana_acum', 'dibujo_jv1',
       'dibujo_acum', 'teatro_jv1', 'teatro_acum', 'educacion_fisica_rd_jv1',
       'educacion_fisica_rd_acum', 'ingles_avanzado_jv1',
       'ingles_avanzado_acum', 'convivencia_jv1'],
      dtype='object')

In [ ]:
#4.1  (Eliminar doble _ _ y reemplazar por _ )
df.columns = df.columns.str.replace("__", "_")
df.columns

Index(['n°', 'codigo', 'estudiante', 'electronica_jv1', 'electronica_acum',
       'programacion_jv1', 'programacion_acum', 'logica_matematica_jv1',
       'logica_matematica_acum', 'quimica_jv1', 'quimica_acum', 'fisica_jv1',
       'fisica_acum', 'trigonometria_jv1', 'trigonometria_acum',
       'informatica_tecnologia_jv1', 'informatica_tecnologia_acum',
       'competencias_ciudadanas_jv1', 'competencias_ciudadanas_acum',
       'ciencias_politicas_economicas_jv1',
       'ciencias_politicas_economicas_acum', 'filosofia_jv1', 'filosofia_acum',
       'educacion_etica_religiosa_jv1', 'educacion_etica_religiosa_acum',
       'lengua_castellana_jv1', 'lengua_castellana_acum', 'dibujo_jv1',
       'dibujo_acum', 'teatro_jv1', 'teatro_acum', 'educacion_fisica_rd_jv1',
       'educacion_fisica_rd_acum', 'ingles_avanzado_jv1',
       'ingles_avanzado_acum', 'convivencia_jv1'],
      dtype='object')

In [ ]:
#PASO 5 — VALIDAR LOS DATOS
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   n°                                  32 non-null     int64
 1   codigo                              32 non-null     int64
 2   estudiante                          32 non-null     object
 3   electronica_jv1                     31 non-null     float64
 4   electronica_acum                    31 non-null     float64
 5   programacion_jv1                    31 non-null     float64
 6   programacion_acum                   31 non-null     float64
 7   logica_matematica_jv1               31 non-null     float64
 8   logica_matematica_acum              31 non-null     float64
 9   quimica_jv1                         31 non-null     float64
 10  quimica_acum                        31 non-null     float64
 11  fisica_jv1                          32 non-null     float64
 12  fisica_acum                         32 non-null     float64
 13  trigonometria_jv1                   31 non-null     float64
 14  trigonometria_acum                  31 non-null     float64
 15  informatica_tecnologia_jv1          31 non-null     float64
 16  informatica_tecnologia_acum         31 non-null     float64
 17  competencias_ciudadanas_jv1         31 non-null     float64
 18  competencias_ciudadanas_acum        31 non-null     float64
 19  ciencias_politicas_economicas_jv1   31 non-null     float64
 20  ciencias_politicas_economicas_acum  31 non-null     float64
 21  filosofia_jv1                       31 non-null     float64
 22  filosofia_acum                      31 non-null     float64
 23  educacion_etica_religiosa_jv1       31 non-null     float64
 24  educacion_etica_religiosa_acum      31 non-null     float64
 25  lengua_castellana_jv1               31 non-null     float64
 26  lengua_castellana_acum              31 non-null     float64
 27  dibujo_jv1                          31 non-null     float64
 28  dibujo_acum                         31 non-null     float64
 29  teatro_jv1                          31 non-null     float64
 30  teatro_acum                         31 non-null     float64
 31  educacion_fisica_rd_jv1             31 non-null     float64
 32  educacion_fisica_rd_acum            31 non-null     float64
 33  ingles_avanzado_jv1                 31 non-null     float64
 34  ingles_avanzado_acum                31 non-null     float64
 35  convivencia_jv1                     31 non-null     object
dtypes: float64(32), int64(2), object(2)
memory usage: 9.1+ KB

In [ ]:
df.describe()

,n°,codigo,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,quimica_acum,...,lengua_castellana_jv1,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum
count,32.000000,3.200000e+01,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,16.500000,2.149557e+06,3.670968,0.915161,3.454839,0.861613,3.135484,0.781935,3.603226,0.898065,...,3.580645,0.892581,3.954839,0.985806,3.790323,0.944194,3.700000,0.922258,3.009677,0.750000
std,9.380832,3.963126e+05,0.623000,0.155539,0.650045,0.161763,0.542555,0.135608,0.490227,0.122839,...,0.382465,0.095428,0.521433,0.130506,0.248133,0.062009,0.531037,0.133784,0.739980,0.184842
min,1.000000,1.510107e+06,2.700000,0.670000,2.600000,0.650000,2.100000,0.520000,2.500000,0.620000,...,2.800000,0.700000,2.700000,0.670000,3.100000,0.770000,2.300000,0.570000,1.600000,0.400000
25%,8.750000,1.810256e+06,3.250000,0.810000,2.900000,0.720000,2.800000,0.700000,3.300000,0.820000,...,3.300000,0.820000,3.600000,0.900000,3.650000,0.910000,3.550000,0.885000,2.500000,0.620000
50%,16.500000,2.160301e+06,3.600000,0.900000,3.300000,0.820000,3.200000,0.800000,3.600000,0.900000,...,3.500000,0.870000,4.000000,1.000000,3.900000,0.970000,3.900000,0.970000,3.000000,0.750000
75%,24.250000,2.600054e+06,4.100000,1.025000,3.950000,0.985000,3.400000,0.850000,4.000000,1.000000,...,3.800000,0.950000,4.400000,1.100000,4.000000,1.000000,4.050000,1.010000,3.600000,0.900000
max,32.000000,2.600084e+06,4.900000,1.220000,4.800000,1.200000,4.100000,1.020000,4.600000,1.150000,...,4.300000,1.070000,4.700000,1.170000,4.100000,1.020000,4.300000,1.070000,4.600000,1.150000

In [ ]:
df = df.dropna()

In [ ]:
df.tail()

,n°,codigo,estudiante,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,...,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum,convivencia_jv1
26,27,2110439,SANCHEZ MADERO JOSEPH ESTEBAN,3.6,0.90,2.8,0.70,3.2,0.80,3.3,...,0.87,3.7,0.92,3.5,0.87,4.3,1.07,2.5,0.62,BS
27,28,1810290,SANCHEZ PAJARO ANDRUS DAVID,4.5,1.12,3.9,0.97,3.4,0.85,3.7,...,1.07,4.0,1.00,3.9,0.97,4.0,1.00,3.6,0.90,AL
28,29,1710252,URIBE JIMENEZ UA ISABEL,4.9,1.22,4.4,1.10,4.0,1.00,4.6,...,1.07,4.2,1.05,3.9,0.97,3.6,0.90,4.3,1.07,SU
29,30,2400311,URREGO MARTINEZ DANNA JULIETH,3.2,0.80,2.9,0.72,2.2,0.55,3.2,...,0.85,2.7,0.67,3.9,0.97,2.7,0.67,1.7,0.42,BS
30,31,1810325,ZAPATA MARQUEZ KLEIMARY JULIANA,4.7,1.17,4.5,1.12,3.8,0.95,4.0,...,1.00,4.6,1.15,4.1,1.02,4.0,1.00,3.3,0.82,SU

In [ ]:
df.shape

(31, 36)

In [ ]:
df.describe()

,n°,codigo,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,quimica_acum,...,lengua_castellana_jv1,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum
count,31.000000,3.100000e+01,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,16.000000,2.141476e+06,3.670968,0.915161,3.454839,0.861613,3.135484,0.781935,3.603226,0.898065,...,3.580645,0.892581,3.954839,0.985806,3.790323,0.944194,3.700000,0.922258,3.009677,0.750000
std,9.092121,4.001751e+05,0.623000,0.155539,0.650045,0.161763,0.542555,0.135608,0.490227,0.122839,...,0.382465,0.095428,0.521433,0.130506,0.248133,0.062009,0.531037,0.133784,0.739980,0.184842
min,1.000000,1.510107e+06,2.700000,0.670000,2.600000,0.650000,2.100000,0.520000,2.500000,0.620000,...,2.800000,0.700000,2.700000,0.670000,3.100000,0.770000,2.300000,0.570000,1.600000,0.400000
25%,8.500000,1.810222e+06,3.250000,0.810000,2.900000,0.720000,2.800000,0.700000,3.300000,0.820000,...,3.300000,0.820000,3.600000,0.900000,3.650000,0.910000,3.550000,0.885000,2.500000,0.620000
50%,16.000000,2.110549e+06,3.600000,0.900000,3.300000,0.820000,3.200000,0.800000,3.600000,0.900000,...,3.500000,0.870000,4.000000,1.000000,3.900000,0.970000,3.900000,0.970000,3.000000,0.750000
75%,23.500000,2.600054e+06,4.100000,1.025000,3.950000,0.985000,3.400000,0.850000,4.000000,1.000000,...,3.800000,0.950000,4.400000,1.100000,4.000000,1.000000,4.050000,1.010000,3.600000,0.900000
max,31.000000,2.600084e+06,4.900000,1.220000,4.800000,1.200000,4.100000,1.020000,4.600000,1.150000,...,4.300000,1.070000,4.700000,1.170000,4.100000,1.020000,4.300000,1.070000,4.600000,1.150000

In [ ]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 30
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   n°                                  31 non-null     int64
 1   codigo                              31 non-null     int64
 2   estudiante                          31 non-null     object
 3   electronica_jv1                     31 non-null     float64
 4   electronica_acum                    31 non-null     float64
 5   programacion_jv1                    31 non-null     float64
 6   programacion_acum                   31 non-null     float64
 7   logica_matematica_jv1               31 non-null     float64
 8   logica_matematica_acum              31 non-null     float64
 9   quimica_jv1                         31 non-null     float64
 10  quimica_acum                        31 non-null     float64
 11  fisica_jv1                          31 non-null     float64
 12  fisica_acum                         31 non-null     float64
 13  trigonometria_jv1                   31 non-null     float64
 14  trigonometria_acum                  31 non-null     float64
 15  informatica_tecnologia_jv1          31 non-null     float64
 16  informatica_tecnologia_acum         31 non-null     float64
 17  competencias_ciudadanas_jv1         31 non-null     float64
 18  competencias_ciudadanas_acum        31 non-null     float64
 19  ciencias_politicas_economicas_jv1   31 non-null     float64
 20  ciencias_politicas_economicas_acum  31 non-null     float64
 21  filosofia_jv1                       31 non-null     float64
 22  filosofia_acum                      31 non-null     float64
 23  educacion_etica_religiosa_jv1       31 non-null     float64
 24  educacion_etica_religiosa_acum      31 non-null     float64
 25  lengua_castellana_jv1               31 non-null     float64
 26  lengua_castellana_acum              31 non-null     float64
 27  dibujo_jv1                          31 non-null     float64
 28  dibujo_acum                         31 non-null     float64
 29  teatro_jv1                          31 non-null     float64
 30  teatro_acum                         31 non-null     float64
 31  educacion_fisica_rd_jv1             31 non-null     float64
 32  educacion_fisica_rd_acum            31 non-null     float64
 33  ingles_avanzado_jv1                 31 non-null     float64
 34  ingles_avanzado_acum                31 non-null     float64
 35  convivencia_jv1                     31 non-null     object
dtypes: float64(32), int64(2), object(2)
memory usage: 9.0+ KB

In [ ]:
#Guardamos
df.to_csv("datos_limpios_pre.csv", index=False)

In [ ]:
from google.colab import files
files.download("datos_limpios_pre.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("datos_limpios_pre.csv")

In [ ]:
df.head()

,n°,codigo,estudiante,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,...,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum,convivencia_jv1
0,1,2500352,ANAYA MARTINEZ SANTIAGO JOSE,3.3,0.82,2.8,0.70,2.2,0.55,4.0,...,0.92,4.5,1.12,3.1,0.77,3.6,0.90,2.8,0.70,AL
1,2,2210053,BENITEZ GUIRAL ISABELLA,3.7,0.92,2.8,0.70,3.5,0.87,3.6,...,0.90,4.5,1.12,3.5,0.87,3.2,0.80,3.1,0.77,AL
2,3,2300038,BENITEZ TIQUE VALENTINA,3.2,0.80,3.7,0.92,3.3,0.82,3.6,...,0.87,4.5,1.12,4.1,1.02,4.1,1.02,3.7,0.92,AL
3,4,2600054,BORRERO GALLEGO THOMAS,2.8,0.70,2.9,0.72,3.1,0.77,2.8,...,0.82,4.0,1.00,3.9,0.97,4.0,1.00,2.8,0.70,BS
4,5,2600055,BRITTON HOWARD ERICK JACOB,3.3,0.82,3.2,0.80,2.5,0.62,3.9,...,0.77,3.9,0.97,3.6,0.90,4.2,1.05,3.0,0.75,AL

In [ ]:
df.columns

Index(['codigo', 'estudiante', 'electronica_jv1', 'electronica_acum',
       'programacion_jv1', 'programacion_acum', 'logica_matematica_jv1',
       'logica_matematica_acum', 'quimica_jv1', 'quimica_acum', 'fisica_jv1',
       'fisica_acum', 'trigonometria_jv1', 'trigonometria_acum',
       'informatica_tecnologia_jv1', 'informatica_tecnologia_acum',
       'competencias_ciudadanas_jv1', 'competencias_ciudadanas_acum',
       'ciencias_politicas_economicas_jv1',
       'ciencias_politicas_economicas_acum', 'filosofia_jv1', 'filosofia_acum',
       'educacion_etica_religiosa_jv1', 'educacion_etica_religiosa_acum',
       'lengua_castellana_jv1', 'lengua_castellana_acum', 'dibujo_jv1',
       'dibujo_acum', 'teatro_jv1', 'teatro_acum', 'educacion_fisica_rd_jv1',
       'educacion_fisica_rd_acum', 'ingles_avanzado_jv1',
       'ingles_avanzado_acum', 'convivencia_jv1'],
      dtype='object')

In [ ]:
#Borrar columna que no es relevante
df = df.drop(columns=["n°"])

In [ ]:
#IDENTIFICAR LA COLUMNA convivencia
[col for col in df.columns if "convivencia" in col]

['convivencia_jv1']

In [ ]:
#PASO 6 CREAR DATAFRAME solo de CONVIVENCIA
df_convivencia = df[['codigo', 'estudiante', 'convivencia_jv1']]

In [ ]:
df_convivencia.head()

    codigo                    estudiante convivencia_jv1
0  2500352  ANAYA MARTINEZ SANTIAGO JOSE              AL
1  2210053       BENITEZ GUIRAL ISABELLA              AL
2  2300038       BENITEZ TIQUE VALENTINA              AL
3  2600054        BORRERO GALLEGO THOMAS              BS
4  2600055    BRITTON HOWARD ERICK JACOB              AL

In [ ]:
#6.1 CREAR DATAFRAME SIN CONVIVENCIA
df_notas = df.drop(columns=['convivencia_jv1'])

In [19]:
df_notas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 34 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   codigo                              31 non-null     int64
 1   estudiante                          31 non-null     object
 2   electronica_jv1                     31 non-null     float64
 3   electronica_acum                    31 non-null     float64
 4   programacion_jv1                    31 non-null     float64
 5   programacion_acum                   31 non-null     float64
 6   logica_matematica_jv1               31 non-null     float64
 7   logica_matematica_acum              31 non-null     float64
 8   quimica_jv1                         31 non-null     float64
 9   quimica_acum                        31 non-null     float64
 10  fisica_jv1                          31 non-null     float64
 11  fisica_acum                         31 non-null     float64
 12  trigonometria_jv1                   31 non-null     float64
 13  trigonometria_acum                  31 non-null     float64
 14  informatica_tecnologia_jv1          31 non-null     float64
 15  informatica_tecnologia_acum         31 non-null     float64
 16  competencias_ciudadanas_jv1         31 non-null     float64
 17  competencias_ciudadanas_acum        31 non-null     float64
 18  ciencias_politicas_economicas_jv1   31 non-null     float64
 19  ciencias_politicas_economicas_acum  31 non-null     float64
 20  filosofia_jv1                       31 non-null     float64
 21  filosofia_acum                      31 non-null     float64
 22  educacion_etica_religiosa_jv1       31 non-null     float64
 23  educacion_etica_religiosa_acum      31 non-null     float64
 24  lengua_castellana_jv1               31 non-null     float64
 25  lengua_castellana_acum              31 non-null     float64
 26  dibujo_jv1                          31 non-null     float64
 27  dibujo_acum                         31 non-null     float64
 28  teatro_jv1                          31 non-null     float64
 29  teatro_acum                         31 non-null     float64
 30  educacion_fisica_rd_jv1             31 non-null     float64
 31  educacion_fisica_rd_acum            31 non-null     float64
 32  ingles_avanzado_jv1                 31 non-null     float64
 33  ingles_avanzado_acum                31 non-null     float64
dtypes: float64(32), int64(1), object(1)
memory usage: 8.4+ KB

In [ ]:
#GUARDAR LOS DOS DATASETS
#Dataset de notas:

df_notas.to_csv("datos_notas.csv", index=False)
df_convivencia.to_csv("datos_convivencia.csv", index=False)

In [ ]:
from google.colab import files
files.download("datos_notas.csv")
files.download("datos_convivencia.csv")

In [2]:
#Abrir archivos de nuevo
from google.colab import files
files.upload()

Saving datos_convivencia.csv to datos_convivencia.csv
Saving datos_notas.csv to datos_notas.csv

{'datos_convivencia.csv': b'codigo,estudiante,convivencia_jv1\n2500352,ANAYA MARTINEZ SANTIAGO JOSE,AL\n2210053,BENITEZ GUIRAL ISABELLA,AL\n2300038,BENITEZ TIQUE VALENTINA,AL\n2600054,BORRERO GALLEGO THOMAS,BS\n2600055,BRITTON HOWARD ERICK JACOB,AL\n2110082,CARDENAS PEREZ DANIEL SANTIAGO,BS\n2500403,CASALLAS HIGUERA EILEEN CATALINA,BS\n2600057,ESQUIVEL RUIZ SARA MELISSA,BS\n2600058,ETREN VEGA TOMAS JOSE,BS\n2600059,GARCIA SAAVEDRA SARAY,BS\n1510107,GOMEZ HUERTAS BRIGITH NICOL,BS\n2600060,GOMEZ LOZANO LUNAPAZ,AL\n2210189,HERNANDEZ ESPINOSA DANIEL ALEJANDRO,BS\n1610112,HERNANDEZ SANABRIA NICOL TATIANA,AL\n1910125,MARTINEZ CALDERON JOSE DAMIAN,BS\n1610146,MONROY SOTO CRISTIAN CAMILO,AL\n2110535,MU\xc3\x91OZ ESPINOSA SARA JULIETH,AL\n1610159,NAVARRO NI\xc3\x91O MARIA FERNANDA,AL\n1910150,NIETO TORRES UVEN CORINA,SU\n1510195,PERDOMO AGUILERA ALEJANDRO,BS\n2600072,PEREZ GONZALEZ ARTURO,BS\n2110549,PINEDA PINEDA ASLY KATERINE,AL\n2600075,PUENTES PAUCAR HANNA SARAI,AL\n1810155,RIOS SANABRIA JUAN SEBASTIAN,AL\n2600084,ROZO RODRIGUEZ JOSE ALEJANDRO,AL\n1610227,SALGADO CAMPO SARA ELISA,AL\n2110439,SANCHEZ MADERO JOSEPH ESTEBAN,BS\n1810290,SANCHEZ PAJARO ANDRUS DAVID,AL\n1710252,URIBE JIMENEZ UA ISABEL,SU\n2400311,URREGO MARTINEZ DANNA JULIETH,BS\n1810325,ZAPATA MARQUEZ KLEIMARY JULIANA,SU\n',
 'datos_notas.csv': b'codigo,estudiante,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,quimica_acum,fisica_jv1,fisica_acum,trigonometria_jv1,trigonometria_acum,informatica_tecnologia_jv1,informatica_tecnologia_acum,competencias_ciudadanas_jv1,competencias_ciudadanas_acum,ciencias_politicas_economicas_jv1,ciencias_politicas_economicas_acum,filosofia_jv1,filosofia_acum,educacion_etica_religiosa_jv1,educacion_etica_religiosa_acum,lengua_castellana_jv1,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum\n2500352,ANAYA MARTINEZ SANTIAGO JOSE,3.3,0.82,2.8,0.7,2.2,0.55,4.0,1.0,2.0,0.5,2.3,0.57,4.1,1.02,3.8,0.95,3.9,0.97,3.0,0.75,2.9,0.72,3.7,0.92,4.5,1.12,3.1,0.77,3.6,0.9,2.8,0.7\n2210053,BENITEZ GUIRAL ISABELLA,3.7,0.92,2.8,0.7,3.5,0.87,3.6,0.9,2.7,0.67,2.7,0.67,3.7,0.92,4.6,1.15,4.3,1.07,3.0,0.75,2.8,0.7,3.6,0.9,4.5,1.12,3.5,0.87,3.2,0.8,3.1,0.77\n2300038,BENITEZ TIQUE VALENTINA,3.2,0.8,3.7,0.92,3.3,0.82,3.6,0.9,3.7,0.92,3.3,0.82,4.5,1.12,4.1,1.02,3.8,0.95,4.9,1.22,4.4,1.1,3.5,0.87,4.5,1.12,4.1,1.02,4.1,1.02,3.7,0.92\n2600054,BORRERO GALLEGO THOMAS,2.8,0.7,2.9,0.72,3.1,0.77,2.8,0.7,2.5,0.62,2.3,0.57,3.5,0.87,3.9,0.97,4.1,1.02,3.1,0.77,2.3,0.57,3.3,0.82,4.0,1.0,3.9,0.97,4.0,1.0,2.8,0.7\n2600055,BRITTON HOWARD ERICK JACOB,3.3,0.82,3.2,0.8,2.5,0.62,3.9,0.97,2.7,0.67,3.3,0.82,4.0,1.0,3.8,0.95,4.1,1.02,4.1,1.02,3.1,0.77,3.1,0.77,3.9,0.97,3.6,0.9,4.2,1.05,3.0,0.75\n2110082,CARDENAS PEREZ DANIEL SANTIAGO,3.5,0.87,3.3,0.82,3.4,0.85,3.5,0.87,3.0,0.75,3.5,0.87,4.1,1.02,4.5,1.12,3.7,0.92,3.1,0.77,4.8,1.2,3.7,0.92,3.6,0.9,4.0,1.0,3.9,0.97,3.8,0.95\n2500403,CASALLAS HIGUERA EILEEN CATALINA,3.4,0.85,3.4,0.85,2.8,0.7,3.9,0.97,2.2,0.55,2.5,0.62,3.5,0.87,3.4,0.85,4.3,1.07,4.9,1.22,4.5,1.12,3.8,0.95,4.5,1.12,4.0,1.0,3.9,0.97,2.7,0.67\n2600057,ESQUIVEL RUIZ SARA MELISSA,3.9,0.97,3.0,0.75,3.4,0.85,3.8,0.95,2.5,0.62,2.7,0.67,3.7,0.92,3.6,0.9,4.3,1.07,5.0,1.25,4.1,1.02,3.7,0.92,3.7,0.92,3.4,0.85,2.7,0.67,2.2,0.55\n2600058,ETREN VEGA TOMAS JOSE,2.7,0.67,2.6,0.65,2.4,0.6,2.5,0.62,2.3,0.57,2.1,0.52,3.3,0.82,2.9,0.72,3.6,0.9,3.0,0.75,2.1,0.52,3.1,0.77,3.3,0.82,3.7,0.92,4.1,1.02,1.6,0.4\n2600059,GARCIA SAAVEDRA SARAY,2.9,0.72,4.3,1.07,2.7,0.67,3.7,0.92,2.4,0.6,2.4,0.6,3.6,0.9,3.6,0.9,4.0,1.0,4.9,1.22,4.8,1.2,3.4,0.85,4.2,1.05,4.0,1.0,2.3,0.57,2.8,0.7\n1510107,GOMEZ HUERTAS BRIGITH NICOL,3.9,0.97,4.1,1.02,3.2,0.8,3.5,0.87,2.7,0.67,2.8,0.7,3.5,0.87,4.4,1.1,4.3,1.07,3.0,0.75,4.6,1.15,3.5,0.87,4.1,1.02,3.4,0.85,2.7,0.67,2.5,0.62\n2600060,GOMEZ LOZANO LUNAPAZ,4.2,1.05,4.8,1.2,4.1,1.02,4.0,1.0,3.7,0.92,3.4,0.85,4.1,1.02,4.8,1.2,4.0,1.0,5.0,1.25,4.7,1.17,4.0,1.0,4.0,1.0,3.8,0.95,4.2,1.05,3.6,0.9\n2210189,HERNANDEZ ESPINOSA DANIEL ALEJANDRO,3.6,0.9,2.8,0.7,2.4,0.6,2.8,0.7,2.0,0.5,2.9,0.72,3.2,0.8,3.3,0.82,3.6,0.9,3.0,0.75,2.8,0.7,3.0,0.75,3.0,0.75,3.5,0.87,3.9,0.97,2.4,0.6\n1610112,HERNANDEZ SANABRIA NICOL TATIANA,3.3,0.82,4.5,1.12,3.4,0.85,4.1,1.02,3.0,0.75,3.3,0.82,3.9,0.97,4.7,1.17,4.0,1.0,5.0,1.25,4.7,1.17,3.3,0.82,4.3,1.07,3.7,0.92,3.5,0.87,3.1,0.77\n1910125,MARTINEZ CALDERON JOSE DAMIAN,2.8,0.7,2.9,0.72,2.9,0.72,2.7,0.67,2.3,0.57,2.6,0.65,3.3,0.82,3.4,0.85,3.8,0.95,3.7,0.92,3.4,0.85,3.6,0.9,4.1,1.02,3.9,0.97,4.2,1.05,2.3,0.57\n1610146,MONROY SOTO CRISTIAN CAMILO,3.8,0.95,3.3,0.82,3.2,0.8,3.3,0.82,3.0,0.75,3.0,0.75,3.4,0.85,3.8,0.95,3.6,0.9,2.9,0.72,4.2,1.05,2.8,0.7,4.3,1.07,3.6,0.9,3.7,0.92,2.4,0.6\n2110535,MU\xc3\x91OZ ESPINOSA SARA JULIETH,2.8,0.7,2.8,0.7,3.0,0.75,3.3,0.82,2.6,0.65,2.6,0.65,3.7,0.92,4.6,1.15,3.6,0.9,3.9,0.97,4.8,1.2,3.4,0.85,3.5,0.87,3.7,0.92,3.5,0.87,2.8,0.7\n1610159,NAVARRO NI\xc3\x91O MARIA FERNANDA,4.0,1.0,2.8,0.7,2.1,0.52,3.4,0.85,2.6,0.65,3.0,0.75,4.3,1.07,3.8,0.95,4.0,1.0,5.0,1.25,4.6,1.15,4.0,1.0,3.5,0.87,3.9,0.97,2.9,0.72,3.0,0.75\n1910150,NIETO TORRES UVEN CORINA,4.7,1.17,4.5,1.12,4.1,1.02,4.3,1.07,4.6,1.15,3.8,0.95,4.6,1.15,4.6,1.15,4.6,1.15,5.0,1.25,5.0,1.25,4.3,1.07,4.4,1.1,4.1,1.02,4.2,1.05,4.6,1.15\n1510195,PERDOMO AGUILERA ALEJANDRO,2.9,0.72,3.1,0.77,2.8,0.7,3.7,0.92,2.0,0.5,2.2,0.55,3.6,0.9,2.8,0.7,4.0,1.0,4.9,1.22,4.7,1.17,3.2,0.8,3.7,0.92,3.7,0.92,3.7,0.92,2.5,0.62\n2600072,PEREZ GONZALEZ ARTURO,4.2,1.05,3.4,0.85,3.4,0.85,3.5,0.87,3.1,0.77,3.4,0.85,3.4,0.85,3.8,0.95,4.0,1.0,4.1,1.02,2.9,0.72,3.3,0.82,3.2,0.8,3.9,0.97,4.0,1.0,3.0,0.75\n2110549,PINEDA PINEDA ASLY KATERINE,4.4,1.1,3.4,0.85,3.3,0.82,4.0,1.0,3.1,0.77,3.3,0.82,4.2,1.05,4.6,1.15,4.6,1.15,5.0,1.25,5.0,1.25,3.9,0.97,4.7,1.17,3.7,0.92,4.0,1.0,2.3,0.57\n2600075,PUENTES PAUCAR HANNA SARAI,4.4,1.1,4.0,1.0,3.6,0.9,4.3,1.07,4.0,1.0,3.6,0.9,4.3,1.07,4.8,1.2,3.9,0.97,4.8,1.2,4.5,1.12,3.4,0.85,4.4,1.1,4.0,1.0,3.8,0.95,4.5,1.12\n1810155,RIOS SANABRIA JUAN SEBASTIAN,3.8,0.95,3.8,0.95,3.6,0.9,4.0,1.0,3.1,0.77,3.0,0.75,4.1,1.02,3.9,0.97,4.3,1.07,4.9,1.22,4.7,1.17,3.8,0.95,3.3,0.82,4.0,1.0,3.7,0.92,3.7,0.92\n2600084,ROZO RODRIGUEZ JOSE ALEJANDRO,3.9,0.97,3.4,0.85,3.1,0.77,3.3,0.82,3.0,0.75,2.9,0.72,3.8,0.95,4.1,1.02,3.8,0.95,4.3,1.07,4.3,1.07,3.3,0.82,3.6,0.9,3.9,0.97,4.1,1.02,3.0,0.75\n1610227,SALGADO CAMPO SARA ELISA,3.5,0.87,3.0,0.75,3.1,0.77,3.4,0.85,3.4,0.85,3.2,0.8,3.9,0.97,4.2,1.05,4.3,1.07,4.2,1.05,4.4,1.1,3.8,0.95,4.6,1.15,4.1,1.02,4.0,1.0,3.7,0.92\n2110439,SANCHEZ MADERO JOSEPH ESTEBAN,3.6,0.9,2.8,0.7,3.2,0.8,3.3,0.82,2.0,0.5,2.8,0.7,3.5,0.87,3.8,0.95,3.5,0.87,3.8,0.95,2.2,0.55,3.5,0.87,3.7,0.92,3.5,0.87,4.3,1.07,2.5,0.62\n1810290,SANCHEZ PAJARO ANDRUS DAVID,4.5,1.12,3.9,0.97,3.4,0.85,3.7,0.92,3.7,0.92,3.3,0.82,4.3,1.07,4.6,1.15,4.4,1.1,5.0,1.25,4.8,1.2,4.3,1.07,4.0,1.0,3.9,0.97,4.0,1.0,3.6,0.9\n1710252,URIBE JIMENEZ UA ISABEL,4.9,1.22,4.4,1.1,4.0,1.0,4.6,1.15,4.6,1.15,3.8,0.95,4.7,1.17,4.8,1.2,4.5,1.12,5.0,1.25,5.0,1.25,4.3,1.07,4.2,1.05,3.9,0.97,3.6,0.9,4.3,1.07\n2400311,URREGO MARTINEZ DANNA JULIETH,3.2,0.8,2.9,0.72,2.2,0.55,3.2,0.8,2.4,0.6,2.9,0.72,3.8,0.95,4.0,1.0,3.2,0.8,4.6,1.15,4.2,1.05,3.4,0.85,2.7,0.67,3.9,0.97,2.7,0.67,1.7,0.42\n1810325,ZAPATA MARQUEZ KLEIMARY JULIANA,4.7,1.17,4.5,1.12,3.8,0.95,4.0,1.0,4.2,1.05,3.6,0.9,3.9,0.97,4.4,1.1,4.5,1.12,5.0,1.25,4.8,1.2,4.0,1.0,4.6,1.15,4.1,1.02,4.0,1.0,3.3,0.82\n'}

In [3]:
import pandas as pd

df_notas = pd.read_csv("datos_notas.csv")
df_convivencia = pd.read_csv("datos_convivencia.csv")

In [4]:
df_convivencia.tail()

     codigo                       estudiante convivencia_jv1
26  2110439    SANCHEZ MADERO JOSEPH ESTEBAN              BS
27  1810290      SANCHEZ PAJARO ANDRUS DAVID              AL
28  1710252          URIBE JIMENEZ UA ISABEL              SU
29  2400311    URREGO MARTINEZ DANNA JULIETH              BS
30  1810325  ZAPATA MARQUEZ KLEIMARY JULIANA              SU

In [6]:
df_notas.tail(2)

,codigo,estudiante,electronica_jv1,electronica_acum,programacion_jv1,programacion_acum,logica_matematica_jv1,logica_matematica_acum,quimica_jv1,quimica_acum,...,lengua_castellana_jv1,lengua_castellana_acum,dibujo_jv1,dibujo_acum,teatro_jv1,teatro_acum,educacion_fisica_rd_jv1,educacion_fisica_rd_acum,ingles_avanzado_jv1,ingles_avanzado_acum
29,2400311,URREGO MARTINEZ DANNA JULIETH,3.2,0.80,2.9,0.72,2.2,0.55,3.2,0.8,...,3.4,0.85,2.7,0.67,3.9,0.97,2.7,0.67,1.7,0.42
30,1810325,ZAPATA MARQUEZ KLEIMARY JULIANA,4.7,1.17,4.5,1.12,3.8,0.95,4.0,1.0,...,4.0,1.00,4.6,1.15,4.1,1.02,4.0,1.00,3.3,0.82

In [8]:
#PASO 7 — TRANSFORMAR A FORMATO LARGO
df_largo = df_notas.melt(
    id_vars=['codigo', 'estudiante'],
    var_name='asignatura_tipo',
    value_name='nota'
)

In [10]:
df_largo.head(2)

    codigo                    estudiante  asignatura_tipo  nota
0  2500352  ANAYA MARTINEZ SANTIAGO JOSE  electronica_jv1   3.3
1  2210053       BENITEZ GUIRAL ISABELLA  electronica_jv1   3.7

In [11]:
#PASO 8 — SEPARAR COLUMNA ejempo : jv1, acum
df_largo[['asignatura', 'tipo']] = df_largo['asignatura_tipo'].str.rsplit('_', n=1, expand=True)

In [24]:
df_largo.tail(1)

      codigo                       estudiante  nota       asignatura  tipo
991  1810325  ZAPATA MARQUEZ KLEIMARY JULIANA  0.82  ingles_avanzado  acum

In [13]:
#PASO 9 — Eliminación de columnas innecesarias : asignatura_tipo
df_largo = df_largo.drop(columns=['asignatura_tipo'])

In [14]:
df_largo.tail(1)

      codigo                       estudiante  nota       asignatura  tipo
991  1810325  ZAPATA MARQUEZ KLEIMARY JULIANA  0.82  ingles_avanzado  acum

In [15]:
#PASO 10 -  DATSET FINAL........................
df_modelo = df_largo.pivot_table(
    index=['codigo', 'estudiante', 'asignatura'],
    columns='tipo',
    values='nota'
).reset_index()

In [21]:
#Organizar columnas
df_modelo = df_modelo[['codigo', 'estudiante', 'asignatura', 'jv1', 'acum']]

In [19]:
df_modelo.columns.name = None

In [26]:
df_modelo.tail(2)

      codigo                     estudiante     asignatura  jv1  acum
494  2600084  ROZO RODRIGUEZ JOSE ALEJANDRO         teatro  3.9  0.97
495  2600084  ROZO RODRIGUEZ JOSE ALEJANDRO  trigonometria  2.9  0.72

In [27]:
df_convivencia.tail(2)

     codigo                       estudiante convivencia_jv1
29  2400311    URREGO MARTINEZ DANNA JULIETH              BS
30  1810325  ZAPATA MARQUEZ KLEIMARY JULIANA              SU

In [31]:
df_largo.to_csv("datos_notas_flargo.csv", index=False)
df_convivencia.to_csv("datos_convivencia.csv", index=False)
df_modelo.to_csv("datos_notas_flimpio.csv", index=False)

In [35]:
from google.colab import files
##files.download("datos_notas.csv")
#files.download("datos_convivencia.csv")
#files.download("datos_notas_flimpio.csv")

In [36]:
df_modelo = df_modelo.drop(columns=['estudiante'])
df_convivencia = df_convivencia.drop(columns=['estudiante'])

In [37]:
df_modelo.head(3)

    codigo                     asignatura  jv1  acum
0  1510107  ciencias_politicas_economicas  4.3  1.07
1  1510107        competencias_ciudadanas  4.4  1.10
2  1510107                         dibujo  4.1  1.02

In [40]:
#df_modelo[df_modelo['codigo'] == 1510107]
df_modelo.head(2)

    codigo                     asignatura  jv1  acum
0  1510107  ciencias_politicas_economicas  4.3  1.07
1  1510107        competencias_ciudadanas  4.4  1.10

In [41]:
df_convivencia.head(2)

    codigo convivencia_jv1
0  2500352              AL
1  2210053              AL

In [42]:
df_modelo.to_csv("datos_modelo.csv", index=False)
df_convivencia.to_csv("datos_convivencia.csv", index=False)

In [43]:
#DESCARGAR ARCHIVOS DEFINITIVOS
from google.colab import files
files.download("datos_modelo.csv")
files.download("datos_convivencia.csv")
#files.download("datos_notas_flimpio.csv")